export const GET_FULL_CONTACT_LIST = 'GET_FULL_CONTACT_LIST';
export const FETCH_RESERVATIONS = 'FETCH_RESERVATIONS';
export const GET_AREA_LIST = 'GET_AREA_LIST';
export const SET_AREA_LOADING_SPINNER = 'SET_AREA_LOADING_SPINNER';
