//areas
export const GET_FULL_CONTACT_LIST = 'GET_FULL_CONTACT_LIST';
export const FETCH_RESERVATIONS = 'FETCH_RESERVATIONS';
export const GET_AREA_LIST = 'GET_AREA_LIST';
export const SET_AREA_LOADING_SPINNER = 'SET_AREA_LOADING_SPINNER';
export const SET_AREAS_REFRESH = 'SET_AREAS_REFRESH';

//auth
export const USER_SIGNUP_SUCCESS = 'USER_SIGNUP_SUCCESS';
export const USER_SIGNUP_FAIL = 'USER_SIGNUP_FAIL';
export const SET_LOGIN_LOADING_TRUE = 'SET_LOGIN_LOADING_TRUE';
export const SET_LOGIN_LOADING_FALSE = 'SET_LOGIN_LOADING_FALSE';
export const USER_LOGGED_IN = 'USER_LOGGED_IN';
export const FETCH_CURRENT_USER = 'FETCH_CURRENT_USER';
export const USER_LOGGED_OUT = 'USER_LOGGED_OUT';
export const CLEAR_FORM_ERROR = 'CLEAR_FORM_ERROR';
